name: onemodel cypress automation run
on:
  push:
      branches: [ master ]
  pull_request:
      branches: [ master ]
  schedule:
    - cron:  '0 11 * * *'

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    env:
       SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
    
    steps:
     - name: Slack Notification
       uses: slackapi/slack-github-actions@v1.26.0
       with:  
          status: ${{ job.status}}
          steps: ${{ toJson(steps)}}
          channel: '#github_workflows'
          if: always()

       
      
     
  
    

    
