name: onemodel cypress automation
on:
  push:
      branches: [ master ]
  pull_request:
      branches: [ master ]
  schedule:
    - cron:  '0 11 * * *'

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4
      - name: cypress.io
        uses: cypress-io/github-action@v2.9.7
        with:
         start: npm start
     
  
    

    
